[package]
name = "adbyss_core"
version = "0.5.2"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
rust-version = "1.56"
description = "Library for Adbyss."
repository = "https://github.com/Blobfolio/adbyss"
publish = false

[dependencies]
ahash = "0.7.*"
argyle = "0.5.*"
dactyl = "0.2.*"
flate2 = "1.0.*"
fyi_msg = "0.9.*"
once_cell = "1.8.*"
rayon = "1.5.*"
regex = "1.5.*"
utc2k = "0.3.*"
write_atomic = "0.2.*"

[dependencies.adbyss_psl]
path = "../adbyss_psl"

[dependencies.ureq]
version = "2.3.*"
default-features = false
features = [ "tls" ]
