[package]
name = "adbyss_core"
version = "0.4.2"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Library for Adbyss."
repository = "https://github.com/Blobfolio/adbyss"
publish = false

[dependencies]
ahash = "0.7.*"
argyle = "0.4.*"
dactyl = "0.1.*"
flate2 = "1.0.*"
fyi_msg = "0.8.*"
once_cell = "1.8.*"
rayon = "1.5.*"
regex = "1.5.*"
utc2k = "0.2.*"
write_atomic = "0.1.*"

[dependencies.adbyss_psl]
path = "../adbyss_psl"

[dependencies.ureq]
version = "2.1.*"
default-features = false
features = [ "tls" ]
