[package]
name = "adbyss_core"
version = "0.3.0"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Library for Adbyss."
repository = "https://github.com/Blobfolio/adbyss"
publish = false

[dependencies]
ahash = "0.7.*"
flate2 = "1.0.*"
lazy_static = "1.4.*"
rayon = "1.5.*"
regex = "1.4.*"

[dependencies.adbyss_psl]
path = "../adbyss_psl"

[dependencies.chrono]
version = "0.4.*"
default-features = false
features = [ "clock", "std" ]

[dependencies.fyi_menu]
git = "https://github.com/Blobfolio/fyi.git"
branch = "feature/next"

[dependencies.fyi_msg]
git = "https://github.com/Blobfolio/fyi.git"
branch = "feature/next"

[dependencies.fyi_num]
git = "https://github.com/Blobfolio/fyi.git"
branch = "feature/next"

[dependencies.tempfile-fast]
git = "https://github.com/FauxFaux/tempfile-fast-rs.git"
rev = "7cd84b2"

[dependencies.ureq]
version = "2.0.*"
default-features = false
features = [ "tls" ]
