[package]
name = "adbyss_core"
version = "0.7.17"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
rust-version = "1.63"
description = "Library for Adbyss."
repository = "https://github.com/Blobfolio/adbyss"
publish = false

[dependencies]
argyle = "0.6.*"
dactyl = "0.4.*"
fyi_msg = "0.10.*"
rayon = "=1.6.1"
regex = "=1.7.0"
ureq = "=2.6.1"
utc2k = "0.5.*"
write_atomic = "0.2.*"

[dependencies.ahash]
version = "0.8.*"
default-features = false

[dependencies.adbyss_psl]
path = "../adbyss_psl"
