[package]
name = "adbyss_core"
version = "0.3.4"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Library for Adbyss."
repository = "https://github.com/Blobfolio/adbyss"
publish = false

[dependencies]
ahash = "0.7.*"
argyle = "0.4.*"
dactyl = "0.1.*"
flate2 = "1.0.*"
fyi_msg = "0.8.*"
lazy_static = "1.4.*"
rayon = "1.5.*"
regex = "1.5.*"
smartstring = "0.2.*"
utc2k = "0.1.*"

[dependencies.adbyss_psl]
path = "../adbyss_psl"

[dependencies.tempfile-fast]
git = "https://github.com/FauxFaux/tempfile-fast-rs.git"
rev = "7cd84b2"

[dependencies.ureq]
version = "2.1.*"
default-features = false
features = [ "tls" ]
