[package]
name = "adbyss_core"
version = "0.2.4"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Library for Adbyss."
repository = "https://github.com/Blobfolio/adbyss"
publish = false

[dependencies]
chrono = "0.4.*"
lazy_static = "1.4.*"
rayon = "1.5.*"
regex = "1.4.*"
tempfile-fast = "0.3.*"

[dependencies.fyi_msg]
git = "https://github.com/Blobfolio/fyi.git"
tag = "v0.5.0"

[dependencies.adbyss_psl]
path = "../adbyss_psl"

[dependencies.ureq]
version = "2.0.*"
default-features = false
features = [ "tls" ]
