[package]
name = "adbyss_core"
version = "0.2.8"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Library for Adbyss."
repository = "https://github.com/Blobfolio/adbyss"
publish = false

[dependencies]
ahash = "0.6.*"
crossbeam-channel = "0.5.*"
flate2 = "1.0.*"
lazy_static = "1.4.*"
rayon = "1.5.*"
regex = "1.4.*"

[dependencies.adbyss_psl]
path = "../adbyss_psl"

[dependencies.chrono]
version = "0.4.*"
default-features = false
features = [ "clock", "std" ]

[dependencies.fyi_msg]
git = "https://github.com/Blobfolio/fyi.git"
tag = "v0.5.4"

[dependencies.fyi_num]
git = "https://github.com/Blobfolio/fyi.git"
tag = "v0.5.4"

[dependencies.tempfile-fast]
git = "https://github.com/FauxFaux/tempfile-fast-rs.git"
rev = "7cd84b2"

[dependencies.ureq]
version = "2.0.*"
default-features = false
features = [ "tls" ]
