[package]
name = "adbyss_core"
version = "0.7.4"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
rust-version = "1.59"
description = "Library for Adbyss."
repository = "https://github.com/Blobfolio/adbyss"
publish = false

[dependencies]
ahash = "=0.7.6"
argyle = "0.6.*"
dactyl = "0.3.*"
fyi_msg = "0.9.*"
rayon = "=1.5.3"
regex = "=1.5.6"
utc2k = "0.5.*"
write_atomic = "0.2.*"

[dependencies.adbyss_psl]
path = "../adbyss_psl"

[dependencies.ureq]
version = "=2.4.0"
default-features = false
features = [ "tls", "gzip" ]
