[package]
name = "adbyss_core"
version = "0.2.0"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Adbyss is a DNS blacklist manager for Linux."
publish = false

[dependencies]
chrono = "0.4.*"
idna = "0.2.*"
lazy_static = "1.4.*"
rayon = "1.5.*"
regex = "1.4.*"
tempfile-fast = "0.3.*"

[dependencies.fyi_msg]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"

[dependencies.publicsuffix]
version = "1.5.*"
default-features = false

[dependencies.strum]
version = "0.19.*"
features = [ "derive" ]

[dependencies.ureq]
version = "1.5.*"
default-features = false
features = [ "tls" ]
