[package]
name = "adbyss_core"
version = "0.9.0"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
rust-version = "1.73"
description = "Library for Adbyss."
repository = "https://github.com/Blobfolio/adbyss"
publish = false

[dependencies]
argyle = "0.6.*"
dactyl = "0.5.*"
fyi_msg = "0.11.*"
rayon = "1.8.*"
regex = "1.10.*"
ureq = "2.7.0"
utc2k = "0.7.*"
write_atomic = "0.5.*"

[dependencies.ahash]
version = "0.8.*"
default-features = false

[dependencies.adbyss_psl]
path = "../adbyss_psl"
