[package]
name = "adbyss_psl"
version = "0.2.9"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "A minimal Public Suffix List hostname validator."
repository = "https://github.com/Blobfolio/adbyss"
publish = false

[build-dependencies]
ahash = "0.6.*"
idna = "0.2.*"

[dependencies]
ahash = "0.6.*"
idna = "0.2.*"
lazy_static = "1.4.*"
