[package]
name = "adbyss_psl"
version = "0.3.6"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "A minimal Public Suffix List hostname validator."
repository = "https://github.com/Blobfolio/adbyss"
readme = "README.md"

[package.metadata.docs.rs]
features = [ "docs-workaround" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin" ]

[build-dependencies]
ahash = "0.7.*"
idna = "0.2.*"
regex = "1.5.*"

[build-dependencies.ureq]
version = "2.1.*"
default-features = false
features = [ "tls" ]

[dependencies]
ahash = "0.7.*"
idna = "0.2.*"
lazy_static = "1.4.*"
smartstring = "0.2.*"

[features]
default = []

# A workaround for Docs.rs; don't enable this if you're a human.
docs-workaround = []
