[package]
name = "adbyss_psl"
version = "0.7.8"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2021"
rust-version = "1.61"
description = "A minimal Public Suffix List hostname validator."
repository = "https://github.com/Blobfolio/adbyss"
readme = "README.md"

[package.metadata.docs.rs]
features = [ "docsrs", "serde" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin" ]

[build-dependencies]
dactyl = "0.4.*"
idna = "0.2.*"
regex = "1.6.*"
wyhash = "=0.5.0"

[build-dependencies.ureq]
version = "2.5.*"
default-features = false
features = [ "tls", "gzip" ]

[dev-dependencies]
brunch = "0.2.*"
serde = "1.0.*"
serde_json = "1.0.*"

[dependencies]
unicode-bidi = "0.3.*"
unicode-normalization = "0.1.*"
wyhash = "=0.5.0"

[dependencies.serde]
version = "1.0.*"
default-features = false
optional = true

[features]
default = []

# The feature "serde" can be enabled to provide (de)/serialize support for
# adbyss_psl::Domain. We can't write it here because the name matches the
# dependency, but it works!
# serde = []

# This is just a workaround for Docs.rs; don't enable this if you're a human or
# the library will not function correctly.
docsrs = []

[[bench]]
name = "psl_parse"
harness = false
