[package]
name = "adbyss_psl"
version = "0.2.2"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "A minimal Public Suffix List hostname validator."
publish = false

[build-dependencies]
ahash = "0.5.*"
idna = "0.2.*"

[dependencies]
ahash = "0.5.*"
idna = "0.2.*"
lazy_static = "1.4.*"
