[package]
name = "adbyss_psl"
version = "0.4.1"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "A minimal Public Suffix List hostname validator."
repository = "https://github.com/Blobfolio/adbyss"
readme = "README.md"

[package.metadata.docs.rs]
features = [ "docs-workaround", "serde" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [ "x86_64-unknown-linux-gnu", "x86_64-apple-darwin" ]

[build-dependencies]
ahash = "0.7.*"
idna = "0.2.*"
regex = "1.5.*"

[build-dependencies.ureq]
version = "2.1.*"
default-features = false
features = [ "tls" ]

[dev-dependencies]
brunch = "0.1.*"
serde = "1.0.*"
serde_json = "1.0.*"

[dependencies]
ahash = "0.7.*"
idna = "0.2.*"
once_cell = "1.8.*"

[dependencies.serde]
version = "1.0.*"
default-features = false
optional = true

[features]
default = []

# A workaround for Docs.rs; don't enable this if you're a human.
docs-workaround = []

[[bench]]
name = "psl_parse"
harness = false
