.TH "ADBYSS" "1" "October 2024" "adbyss v0.14.0" "User Commands"
.SH NAME
ADBYSS \- Manual page for adbyss v0.14.0.
.SH DESCRIPTION
Adbyss is a DNS blacklist manager for Linux.
.SS USAGE:
.TP
adbyss [FLAGS] [OPTIONS]
.SS FLAGS:
.TP
\fB\-\-disable\fR
Remove *all* Adbyss entries from the hostfile.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Suppress the success message after updating the hostfile.
.TP
\fB\-\-show\fR
Print a sorted blackholable hosts list to STDOUT, one per line.
.TP
\fB\-\-stdout\fR
Print the would\-be hostfile to STDOUT instead of writing it to disk.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.TP
\fB\-y\fR, \fB\-\-yes\fR
Non\-interactive mode; answer "yes" to all prompts.
.SS OPTIONS:
.TP
\fB\-c\fR, \fB\-\-config\fR <FILE>
Use this configuration instead of /etc/adbyss.yaml.
.SS GLOBAL:
.TP
Additional settings are stored in /etc/adbyss.yaml. Edit those to set your preferred global runtime behaviors.
.SS SOURCE LISTS:
.TP
\fBAdAway\fR
<https://adaway.org/>
.TP
\fBSteven Black\fR
<https://github.com/StevenBlack/hosts>
.TP
\fBYoyo\fR
<https://pgl.yoyo.org/adservers/>
