.TH "ADBYSS" "1" "November 2020" "Adbyss v0.1.8" "User Commands"
.SH NAME
Adbyss \- Manual page for adbyss v0.1.8.
.SH DESCRIPTION
Adbyss is a DNS blacklist manager for Linux.
.SS USAGE:
.TP
adbyss [FLAGS] [OPTIONS]
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-\-no\-backup\fR
Do *not* back up the hostfile when writing changes.
.TP
\fB\-\-no\-preserve\fR
Do *not* preserve custom entries from the hostfile when writing changes.
.TP
\fB\-\-no\-summarize\fR
Do *not* summarize changes after write.
.TP
\fB\-\-stdout\fR
Print compiled hostfile to STDOUT.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.TP
\fB\-y\fR, \fB\-\-yes\fR
Non\-interactive mode; answer "yes" to all prompts.
.SS OPTIONS:
.TP
\fB\-c\fR, \fB\-\-config\fR <FILE>
Use this configuration instead of /etc/adbyss.yaml.
.SS GLOBAL:
.TP
Additional settings are stored in /etc/adbyss.yaml. Edit those to set your preferred global runtime behaviors.
.SS SOURCE LISTS:
.TP
\fBAdAway\fR
<https://adaway.org/>
.TP
\fBSteven Black\fR
<https://github.com/StevenBlack/hosts>
.TP
\fBYoyo\fR
<https://pgl.yoyo.org/adservers/>
